[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "22"
  NITRO_PRESET = "netlify"
  NPM_FLAGS = "--legacy-peer-deps"
